name: Publish and Test to TestPyPI

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]
  workflow_dispatch:

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'  # 使用するPythonのバージョン
  
        - name: Install Poetry
          run: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
  
        - name: Install dependencies
          run: |
            poetry install

        - name: publish package to TestPyPI
          run: |
            poetry config repositories.testpypi https://test.pypi.org/legacy/
            poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN}} 
            poetry publish --build --repository testpypi

        - name: パッケージ公開後の待機
          run: sleep 120 

  test_install:
    runs-on: ubuntu-latest
    needs: build_publish

    steps:
      - name: Python のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 必要なパッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install sudachidict_full
          pip install -i https://test.pypi.org/simple/ yurenizer

      - name: インストールされたパッケージのバージョン確認
        run: |
          pip show yurenizer

      - name: download synonym file
        run: |
            curl -L -f -o synonyms.txt https://raw.githubusercontent.com/WorksApplications/SudachiDict/refs/heads/develop/src/main/text/synonyms.txt
            if [ ! -f synonyms.txt ]; then
                echo "Failed to download synonyms.txt"
                exit 1
            fi

      - name: テストスクリプトの実行
        run: |
          echo 'from yurenizer import SynonymNormalizer, NormalizerConfig' > test.py
          echo 'normalizer = SynonymNormalizer(synonym_file_path="synonyms.txt")' >> test.py
          echo 'text = "「パソコン」は「パーソナルコンピュータ」の「synonym」で、「パーソナル・コンピュータ」と表記することもあります。"' >> test.py
          echo 'print(normalizer.normalize(text))' >> test.py
          python test.py